baseURL = 'https://kbinkenaid.github.io/Kblog/'
languageCode = 'en-us'
title = 'Blog'

theme = "ananke"

[params]
  mainSections = ["posts"]

[params.ananke]
  show_recent_posts = true
  recent_posts_number = 10

[publish]
github = "Kbinkenaid/Kblog"
branch = "gh-pages"
commit = true
